### ISSUE TITLE
Convert list of methods to table

### ISSUE THREAD

**Issue by greffgreff** [HBO-i/ictresearchmethods.nl#166]
### Describe the problem

The new redesign of the methods overview page is a bit harder to view in this list view format. The page in question: https://ictresearchmethods.nl/methods-overview/

### Describe the proposed solution

To converting the list into a table, much like the previous design: 
![Framework3](https://github.com/HBO-i/ictresearchmethods.nl/assets/56337726/7c9d1b9e-b5f9-4459-b9b3-954dbfa042d2)

### Importance

would make my life easier

**Comment by jochemvogel** [comment]
Will try to realise this in the coming weeks. Still have to find a way to make it accessible for mobile devices as well, but I'll figure it out. Thanks for the suggestion!

**Comment by jochemvogel** [comment]
@greffgreff I created a new version of it. Very comparable with the old version, but more responsive: https://deploy-preview-191--test-ictresearchmethods.netlify.app/methods-overview/

**Comment by greffgreff** [comment]
It somehow feels better to look at compared to the older version!
