### ISSUE TITLE
Fill in placeholder text

### ISSUE THREAD

**Issue by QazCetelic** [HBO-i/ictresearchmethods.nl#169]
### Describe the bug

Several methods such as “Library: Literature study” still contain placeholder text.

### Reproduction

View source in Github / visit v2.ictresearchmethods.nl

### Expected Behavior

Non-placeholder text

### System Information

Site: v2.ictresearchmethods.nl

### Severity

annoyance

**Comment by jochemvogel** [comment]
Thanks! Changed it in https://github.com/HBO-i/ictresearchmethods.nl/pull/168 and will be live on Friday.

**Comment by QazCetelic** [comment]
Thanks. I hadn't seen the pull request yet, I'll use the deployment preview until then.
