### ISSUE TITLE
Method Brainstorm & Joker contains the contents of Code review

### ISSUE THREAD

**Issue by jookzie** [HBO-i/ictresearchmethods.nl#176]
### Describe the bug

Method [Brainstorm](https://ictresearchmethods.nl/workshop/brainstorm/) & [Joker](https://ictresearchmethods.nl/extra/joker/)contains the contents of [Code review](https://ictresearchmethods.nl/workshop/code-review).

### Reproduction

Visit [https://ictresearchmethods.nl/workshop/brainstorm/](https://ictresearchmethods.nl/workshop/brainstorm/)

### Expected Behavior

Get the contents of [Brainstorm method](https://web.archive.org/web/20220818004731/https://ictresearchmethods.nl/Brainstorm) / [Joker](https://web.archive.org/web/20220818015924/https://ictresearchmethods.nl/Joker)

### System Information

irrelevant

### Severity

annoyance

**Comment by jookzie** [comment]
Also Document analysis & A/B testing are showing the contents of Available product analysis

**Comment by NoWarries** [comment]
This issue appears to be related to #173. Maybe @jochemvogel could merge these together.
