### ISSUE TITLE
The website had a beautful design and a clear overview of the methods

### ISSUE THREAD

**Issue by ErwinBell** [HBO-i/ictresearchmethods.nl#179]
### Describe the bug

Now it hasn't...
Now it has a 'quick overview' in plain black and white text without colours separating the categories.
The previous site looked a lot friendlier than the current one.

### Reproduction

Compare the current site with this:
https://web.archive.org/web/20210613183511/https://ictresearchmethods.nl/Methods

How is the current site better?

### Expected Behavior

A friendly, cheerful website giving positive vibes about using research methods in HBO Education.

### System Information

Apple M1 Max
MacOS 13.5.2 (22G91)
Firefox 118.0.1 (64-bit)

### Severity

annoyance

### Additional Information

What was the problem that you were trying to solve with the new design? Was there a problem? How was the new 'design' validated? Do the developers and designers of the new website used the methods mentioned?

**Comment by NoWarries** [comment]
Duplicate of #166 

I do agree that the updated version is currently harder and more confusing to navigate. But I think with the necessary changes it could actually be better than the old wiki style website.

Also a little hint 😉 you can still access the old website via https://oud.ictresearchmethods.nl/Methods (a subdomain which they should keep up as long as maintainable in my opinion)

**Comment by jochemvogel** [comment]
On addition to @NoWarries, we showed the new design during the HBO I Job Event, two weeks ago. The reactions were similar: the old wiki needed a redesign, but a few things should be the same.

Little background: I created this website for myself to get a better overview of the methods, and the HBO I Foundation decided to use it as the official resource. Because of that we need feedback of the users. Currently we're at that phase now. Thanks! 

I created a new issue specifically related to the quick overview (https://github.com/HBO-i/ictresearchmethods.nl/issues/181). I will have a look at it the coming week. 

Please create more issues if you come across some annoyance. We'd love to hear feedback, seriously. 🙂

**Comment by jochemvogel** [comment]
Created a ticket for this issue (https://github.com/HBO-i/ictresearchmethods.nl/issues/181), will close it now. Thanks.

**Comment by uranderu** [comment]
> Also a little hint 😉 you can still access the old website via https://oud.ictresearchmethods.nl/Methods (a subdomain which they should keep up as long as maintainable in my opinion)

Not related to this issue, sorry for that, but maybe put a banner somewhere with this information? I was searching and searching for the old website and I could only find this new one. Which I thought was an unofficial one.

Edit: I know see the paragraph under the Methods header, it is there, but in my opinion it is very easily missed.

**Comment by NoWarries** [comment]
> > Also a little hint 😉 you can still access the old website via https://oud.ictresearchmethods.nl/Methods (a subdomain which they should keep up as long as maintainable in my opinion)
> 
> Not related to this issue, sorry for that, but maybe put a banner somewhere with this information? I was searching and searching for the old website and I could only find this new one. Which I thought was an unofficial one.
> 
> Edit: I know see the paragraph under the Methods header, it is there, but in my opinion it is very easily missed.

I fully agree with you. This information should be placed in an Alert component idealy. Or maybe an option in the sidenav? Probably both. I suggest you make a [feature request](https://github.com/HBO-i/ictresearchmethods.nl/issues/new?assignees=&labels=&projects=&template=feature_request.yml) for this.

**Comment by uranderu** [comment]
> I fully agree with you. This information should be placed in an Alert component idealy. Or maybe an option in the sidenav? Probably both. I suggest you make a [feature request](https://github.com/HBO-i/ictresearchmethods.nl/issues/new?assignees=&labels=&projects=&template=feature_request.yml) for this.

For your information, I made a feature request at #183
