### ISSUE TITLE
Make it clearer that this is the new official site, with a clearer link to the old one

### ISSUE THREAD

**Issue by uranderu** [HBO-i/ictresearchmethods.nl#183]
### Describe the problem

As talked about in #179 it was unclear to me (and others) that there is a new version of the site and that you can find the old one on another subdomain. Currently there is a paragraph that kind of explains this with a link to the old version. But this is in my opinion very easily missed. And seeing as this site does not yet have all the information of the old one, I think it would benefit everyone if this was made more clear.

### Describe the proposed solution

I am not an UX designer, but I think a banner in the header of every page would be the most clear. Maybe in yellow so that it looks like a warning. Something along the lines of: "You're browsing the new improved version of the website, not everything is already here so click here to go to the old version."

Maybe retain the banner for a while even when all information is here, just so that people know this is the new official one.

### Importance

nice to have

**Comment by jochemvogel** [comment]
@uranderu Good point and I agree! I've added something very quick that might help. At least it is better than what we currently have. What do you think?

1. Added it to the menu (open in new tab)
2. Added the 'new site copy' to every category page, not only to all methods.

<img width="1912" alt="image" src="https://github.com/HBO-i/ictresearchmethods.nl/assets/34123512/9383500a-d02d-43a3-918c-885ade56055c">

**Comment by uranderu** [comment]
Sorry for the late comment, but I like this. Not too much in your face and especially the "Old Wiki" link in the navbar makes things really clear to me. Thanks for your quick work!
