### ISSUE TITLE
Document 'how to cite'

### ISSUE THREAD

**Issue by jochemvogel** [HBO-i/ictresearchmethods.nl#198]
https://oud.ictresearchmethods.nl/How_to_cite

Either in the README or on the website (/about)

**Comment by jochemvogel** [comment]
Apparently it is already on this link https://ictresearchmethods.nl/about/ 🙈

**Comment by ralphniels** [comment]
Yes, but apparantly it needs a more prominent place on the website, because students keep referring to Jochem Vogel as only author. As much as I appreciate your work, this credit does not really fit reality ;-)
