### ISSUE TITLE
Harmonize wiki based web components

### ISSUE THREAD

**Issue by NoWarries** [HBO-i/ictresearchmethods.nl#199]
### Describe the problem

I feel like currently the website is trying to be to much at the same time. It includes various elements that are based on the old wiki design. Which simply do not fit or feel out of place in the modern website design.

Example 1:
![Screenshot 2023-10-30 at 16-49-31 ICT Research Methods — Methods Pack for Research in ICT](https://github.com/HBO-i/ictresearchmethods.nl/assets/99080092/f0c47b80-be20-4dff-88a9-903c8e562129)

Example 2:
![Screenshot 2023-10-30 at 16-49-43 ICT Research Methods — Methods Pack for Research in ICT](https://github.com/HBO-i/ictresearchmethods.nl/assets/99080092/2f407d4b-9453-424b-8b32-b1c2d1c28e21)

### Describe the proposed solution

I think it would help if the tables used one single design. I feel like the first example in particular works well on the site. The second one feels like a completely different component from a completely different site (opionion ofc)

### Importance

nice to have

### Additional Information

Kind of unrelated. But I feel like the mix match of table and list in the methods page a bit confusing.
I am on the 'all methods' page and information is presented as a list I click on a tab and the entire way of displaying information is different.

**Comment by jochemvogel** [comment]
Agreed, but received too much feedback that the users preferred old wiki style. Also saw it in the statistics; too many users are using the old site. When that's the case, I do think you should reconsider your design choices.

Although, I agree with the mix of different styles. Don't like it as well. Will think about it, but I got feedback that it is clear right now, and users can use it as they wished. Will come back on this. Thanks for mentioning!

**Comment by NoWarries** [comment]
I think the users are not so much missing the old design. But the functionality it brings. I understand the table is needed as I use it myself. But personally I would not mind a more modern look. Example 1 looks great on the website in my opinion. Example 2 does less

But that's just me guessing honestly. Maybe we can do a survey somehow.

**Comment by jochemvogel** [comment]
I do agree with you on that. Let me focus on redesigning the **methods per phase** page first, I think that one should have priority now. Works for now, but it feels and looks old-ish.

**Comment by jochemvogel** [comment]
I made a few designs and will decide the implementation with HBO-I after their holiday.
