### ISSUE TITLE
HBO-i logo in dark mode

### ISSUE THREAD

**Issue by ralphniels** [HBO-i/ictresearchmethods.nl#200]
### Describe the bug

When in dark mode, the HBO-i logo keeps its white background. I don't know if HBO-i allows modifications to its logo, but it would look better if the background would match the site's dark background.

Before:
<img width="192" alt="image" src="https://github.com/HBO-i/ictresearchmethods.nl/assets/1544179/13824a93-2975-4a27-8dc9-878f75f8e774">

After:
<img width="192" alt="image" src="https://github.com/HBO-i/ictresearchmethods.nl/assets/1544179/b90f1539-0015-4104-98d4-a96295f780ef">

### Reproduction

Open site, click dark mode selector.

### Expected Behavior

Show a logo that fits the dark style.

### System Information

_Not relevant._

### Severity

annoyance

**Comment by jochemvogel** [comment]
@ralphniels Thanks for the suggestion! The white background was just a temporary fix. Didn't like the contrast without a background. So I prefer a dark mode modified logo for HBO-I, but I don't know if that one is available, or that I should create one.

**Comment by ralphniels** [comment]
> @ralphniels Thanks for the suggestion! The white background was just a temporary fix. Didn't like the contrast without a background. So I prefer a dark mode modified logo for HBO-I, but I don't know if that one is available, or that I should create one.

I'll ask HBO-i!
