### ISSUE TITLE
The new 'Methods per project phase' does not match the old page; the new page contains misplaced methods.

### ISSUE THREAD

**Issue by ghost** [HBO-i/ictresearchmethods.nl#201]
Some examples:
- Ethical Check is placed in the 'Problem Definition' column. While it misses in the 'Evaluation' column.
- A/B testing is placed in the 'Problem Definition' column. While it misses in the 'Realisation' column.
- etc

Is this intentional? Or a bug.

**Comment by jochemvogel** [comment]
@jovabel Thanks! Wasn't aware of that. You can change it in the markdown files: https://github.com/HBO-i/ictresearchmethods.nl/tree/master/src/content/methods/text
