### ISSUE TITLE
Drie schalen toevoegen aan alle methoden

### ISSUE THREAD

**Issue by jorg-janssen** [HBO-i/ictresearchmethods.nl#202]
### Describe the problem

Onderaan de fysieke kaartjes staan drie schalen uit het oorspronkelijke triangulation framework. Deze helpen bij het vinden van een geschikte methode voor jouw onderzoek. Deze ontbreken bij de methoden hier op de website.

![afbeelding](https://github.com/HBO-i/ictresearchmethods.nl/assets/36731675/93197764-b3f0-4377-baab-b561acb4f05f)

### Describe the proposed solution

De drie schalen toevoegen aan ieder kaartje. Qua uiterlijk een op een mooie grafische manier zoals op de fysieke kaartjes, maar onder water met een numerieke waarde zodat deze ook gebruikt kunnen worden in een filterfunctie.

### Importance

would make my life easier

**Comment by ralphniels** [comment]
Dat deze informatie niet online beschikbaar is, terwijl deze wel op de kaartjes staat, is inderdaad een gemis. Ik geef deze een hoge prioriteit. @jochemvogel , kun jij een voorstel doen voor hoe we dit mooi op de site kunnen opnemen? Ik zou kiezen voor getallen (bijv. percentages of fracties) in de bronbestanden, zodat de info later ook via een andere manier te ontsluiten is (bijv. opnemen in zoekfuncties/filteropties, zoals in issue #203 ).

**Comment by jochemvogel** [comment]
@ralphniels Design-wise zou mijn voorkeur uit gaan naar een vergelijkbaar ontwerp als op de kaartjes. 
<img width="590" alt="image" src="https://github.com/user-attachments/assets/aa7a1d4b-d4f4-4292-83db-054314ae69ef">

Zou nog met verschillende kleuren kunnen, maar ik vind 1 kleur consistenter, en de tekst zegt al genoeg.
<img width="480" alt="image" src="https://github.com/user-attachments/assets/b1c393c0-035e-4ab8-88ba-d0aeab3bc205">

**Technisch:**
Dit lijkt mij het fijnst is om mee te werken
```
scales: [
  { name: "inspiration_data", value: 50 },
  { name: "expertise_fit", value: 75 },
  { name: "overview_certainty", value: 30 }
]
```

Middels bijv. `name.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1));` kun je er `["Inspiration", "Data"]` van maken, en weer gebruiken in de UI.

Valt later altijd nog aan te passen. Persoonlijk vind ik deze manier ook toekomstbestendig (o.a. voor zoek/filter functionaliteit)

Kun je na de vakantie hier feedback op geven? Zodra akkoord, zal ik het implementeren. Thanks!

**Comment by ralphniels** [comment]
@jochemvogel Prima voorstel zo, ik zou inderdaad de kleuren hetzelfde doen als op de fysieke kaartjes.
