### ISSUE TITLE
Openingstekst op landing page is weer verdwenen!

### ISSUE THREAD

**Issue by vkreuzen** [HBO-i/ictresearchmethods.nl#206]
### Describe the bug

Openingstekst stond er na wijziging, maar is nu niet meer te zien op de landingpage. Deze moet terug

### Reproduction

Ga naar de landingpage

### Expected Behavior

Openingtekst

### System Information

Any browser

### Severity

serious, but I can work around it

**Comment by jochemvogel** [comment]
@vkreuzen Welke tekst bedoel je? Deze?

As an ICT student or professional, you need to solve all kind of ICT challenges. Answering the questions and tackling the problems or opportunities of your ICT project requires research and often a combination of various ICT research methods. The toolkit on this website offers you a set of possible research methods and a framework to select the appropriate (combination of) methods.

**Comment by vkreuzen** [comment]
Yes, die zien we niet meer
