### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Tazi0** [HBO-i/ictresearchmethods.nl#209]
### Describe the problem

Everything is writen in english while most users are dutch, some german and french.

### Describe the proposed solution

Using a library to extend the website for i18n

### Importance

would make my life easier

**Comment by jochemvogel** [comment]
Thanks @Tazi0! This shouldn't have a high priority, but I do think it will indeed make life easier for a lot of users. 🙂

**Comment by ralphniels** [comment]
It was a deliberate choice to make the texts available (only) in English: we assume that the target audience (Dutch students) are fluent _enough_ in English to use the cards. Multilingualism is great, but comes at the cost of having to keep things synchronized. Priority to low.

**Comment by Tazi0** [comment]
Thanks for the reply @ralphniels, what was the reason for choosing English? Sure, most Dutch students are fluent enough in English. But your target audience is Dutch, wouldn't Dutch therefore be the priority language.

For gaining a global audience, it's great to choose English since it's a global language.

What I've noticed is that most of my friends (while studying) we find the conflicting translations from Dutch (course material) to English (the website) a mess to deal with.

Priority low is understandable

**Comment by ralphniels** [comment]
@Tazi0 : I don't think there are minutes available, but as I recall, the general idea was that most literature is written in English and that some schools teach courses in English to foreign students. Also, we based our card set on the [CMD set](https://cmdmethods.nl) that was written in English.

A partial solution could be translating the method titles to Dutch to match with Dutch course material, but I'm not sure we should do that. I'd suggest to do it the other way around and refer to English method titles in Dutch course material. That's the way I usually do it when developing material for my courses.
