### ISSUE TITLE
Documentation of Available Product Analysis

### ISSUE THREAD

**Issue by ErwinBell** [HBO-i/ictresearchmethods.nl#212]
Part of: Library
Documentation for: Available Product Analysis

Currently, this method starts with the following sentence:
"_Find out if what you are planning to do has already been done (in full or in part) by someone else._"

This implies a similar research as Competitive Analysis.
Rewriting the first sentence would make it clearer and more suitable to also use it for comparing the most suitable tools for a project.
For example one could then use it to compare game engines for which game engine is the most suitable for the project.

**Comment by jochemvogel** [comment]
@ralphniels @vkreuzen

**Comment by ralphniels** [comment]
Thanks for your suggestion. We have considered your proposed changes, however, we see no reason to change the description: the current description accurately describes the method. @ErwinBell
