### ISSUE TITLE
Logo jumps when switching between light and dark mode

### ISSUE THREAD

**Issue by KevinDaGame** [HBO-i/ictresearchmethods.nl#216]
### Describe the bug

The logo jumps 10 px when switching between light and dark mode on desktop. 
The cause seems to be a padding of 0.25rem on the light mode variant from the .logo class on the svg, which is not applied on the dark mode variant.

### Reproduction

1. Open the site on a desktop
2. Note the distance between the left side of the screen and the logo
3. switch to light/dark mode
4. Note the distance between the left side of the screen and the logo
5. See that these numbers are not the same

### Expected Behavior

The logo shouldn't jump when switching between light and dark mode

### System Information

Windows 11
MS Edge v121

### Severity

annoyance

**Comment by jochemvogel** [comment]
Thanks for noticing, but the source files of the svgs are different. Small thing, so I won't fix it.
