### ISSUE TITLE
Research pattern navigator "questions" are incorrect

### ISSUE THREAD

**Issue by MPFGlaser** [HBO-i/ictresearchmethods.nl#219]
### Describe the bug

The example questions shown below the research patterns in the [research pattern navigator](https://ictresearchmethods.nl/research-pattern-navigator/) are incorrect for "Validate" and "Choose fitting technology".  
"Validate" has the question "How do I choose the right technologies for my project?", while "Choose fitting technology" has "How do I monitor the quality of my solution?". This should be swapped around. The other example questions seem to be in the right place, though.  
It appears that the questions are correct on [the old version](https://oud.ictresearchmethods.nl/Research_Pattern_Navigator), though.

### Reproduction

Visit the [research pattern navigator](https://ictresearchmethods.nl/research-pattern-navigator/)

### Expected Behavior

"Validate" would have "How do I monitor the quality of my solution?" as its question, and "Choose fitting technology" would have "How do I choose the right technologies for my project?" as its question.

### System Information

Windows 10, Firefox Developer Edition (124.0b7 (64-bit))

### Severity

serious, but I can work around it

### Additional Information

Not a functionality-breaking bug, but one in the text itself that may lead students to the wrong direction.

**Comment by jochemvogel** [comment]
Thanks!
