### ISSUE TITLE
Documentation of Methods > Prototyping > Ingredients

### ISSUE THREAD

**Issue by MathijnG** [HBO-i/ictresearchmethods.nl#220]
Documentation for: [Methods > Prototyping > Ingredients]

**Details**
The ingredients of the prototyping method are missing on the **new website**

![image](https://github.com/HBO-i/ictresearchmethods.nl/assets/39953491/d5bf0a93-fc61-4d2f-bb51-1f6df588e8b5)

**Comment by jochemvogel** [comment]
Thanks!
