### ISSUE TITLE
cmd + k focust browser zoekbalk i.p.v. website zoekbalk

### ISSUE THREAD

**Issue by jejbuitenhuis** [HBO-i/ictresearchmethods.nl#231]
### Describe the bug

Wanneer <kbd>cmd</kbd> + <kbd>k</kbd> wordt gebruikt om te zoeken in de zoekbalk van de website, gaat de focus uiteindelijk naar de zoekbalk van de browser.

### Reproduction

1. Ga naar https://www.ictresearchmethods.nl/
2. Druk op <kbd>cmd</kbd> + <kbd>k</kbd>
3. Focus gaat naar de website zoekbalk
4. Gelijk daarna gaat de focus naar de zoekbalk van de browser

### Expected Behavior

1. Ga naar https://www.ictresearchmethods.nl/
2. Druk op <kbd>cmd</kbd> + <kbd>k</kbd>
3. Focus gaat naar de website zoekbalk

### System Information

- macOS Ventura 13.6.6
- Firefox versie 124.0.2

### Severity

annoyance

### Additional Information

Dit is waarschijnlijk op te lossen door in [de event handler](https://github.com/HBO-i/ictresearchmethods.nl/blob/4c779596c4b55367e85a5ab82123e1670bbb6480/src/routes/%2Blayout.svelte#L54) [`event.preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) aan te roepen.

**Comment by jochemvogel** [comment]
Updated the `CMD + K` functionality with a `/`, which you see more often lately. Still possible to use CMD + K. Thanks for noticing!
